[phases.setup]
nixPkgs = ["php82Packages.composer", "mysql-client", "nodejs", "python311Packages.supervisor"]


[phases.build]
cmds = [
  "chmod +x /assets/start.sh"
]

[start]
cmd = "/assets/start.sh"
