[phases.setup]
nixPkgs = ["python311Packages.supervisor", "mysql80"]

[phases.build]
cmds = [
  "mkdir -p /etc/supervisor/conf.d/",
  "cp /assets/worker-*.conf /etc/supervisor/conf.d/",
  "cp /assets/supervisord.conf /etc/supervisord.conf",
  "chmod +x /assets/start.sh"
]

[start]
cmd = "/assets/start.sh"
