[program:worker-laravel]
directory=/var/www
command=php artisan queue:work --sleep=3 --tries=3 --queue=default
user=www-data
autorestart=true
stopasgroup=true
killasgroup=true
startsecs=5
priority=30
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
; لو ما عندك Queue فعّالة، غيّر autostart إلى false
autostart=false
